azur/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', WebPagesViewList.as_view(), name='home'),
    path('v2', WebView.as_view(), name='home2')
]

azur_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('azur.urls'))
]

azur/models.py
from django.db import models


class WebPage(models.Model):
    visited = models.DateTimeField()
    tag = models.CharField(max_length=128)
    url = models.TextField()
    domain = models.TextField()
    time_to_load = models.IntegerField()
    load_code = models.IntegerField()
    size = models.BigIntegerField()

    class Meta:
        verbose_name_plural = 'web pages'

    def __str__(self):
        return self.domain

azur/views.py
from django.views.generic import ListView
from .models import WebPage
from django.db.models import Q, Count
from .filters import *


class WebPagesViewList(ListView):
    model = WebPage
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = PageFilter(self.request.GET, queryset=self.get_queryset())
        return context


class WebView(ListView):
    model = WebPage
    template_name = 'index.html'

    def get_queryset(self):
        queryset = WebPage.objects.all()
        tag = self.request.GET.get('tag')
        domain = self.request.GET.get('domain')
        size = self.request.GET.get('size')
        load_code = self.request.GET.get('load_code')
        ch_tag = self.request.GET.get('ch_tag')
        ch_dom = self.request.GET.get('ch_dom')
        ch_lc = self.request.GET.get('ch_lc')
        if tag or domain or size or load_code is not None:
            if tag is not '':
                queryset = queryset.filter(tag__contains=tag)
            if domain is not '':
                queryset = queryset.filter(domain=domain)
            if size is not '':
                queryset = queryset.filter(size__lte=size)
            if load_code is not '':
                if 'XX' in str(load_code).upper():
                    queryset = queryset.filter(load_code__range=(int(load_code[0]) * 100, int(load_code[0]) * 100 + 99))
                else:
                    queryset = queryset.filter(load_code=load_code)
        if ch_tag == 't':
            queryset = queryset.values('tag').order_by('tag').annotate(count=Count('tag'))
        if ch_dom == 't':
            queryset = queryset.values('domain').order_by('domain').annotate(count=Count('domain'))
        if ch_lc == 't':
            queryset = queryset.values('load_code').order_by('load_code').annotate(count=Count('load_code'))
        return queryset

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% load bootstrap %}
<div class="container">
    <form method="get">
        {{ filter.form|bootstrap }}
    <button type="submit">Search</button>
            <ul>
          {% for page in filter.qs %}
            <li>
              {{ page.visited }}, {{ page.tag }}, {{ page.url }}, {{ page.domain }}, {{ page.time_to_load }}, {{ page.load_code }}, {{ page.size }}
            </li>
          {% endfor %}
        </ul>
</div>

</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'home2' %}" method="get">
        <input name="tag" type="text" placeholder="tag"> <input type="checkbox" name="ch_tag" value="t"><br>
        <input name="domain" type="text" placeholder="domain"> <input type="checkbox" name="ch_dom" value="t"><br>
        <input name="load_code" type="text" placeholder="load code"> <input type="checkbox" name="ch_lc" value="t"><br>
        <input name="size" type="text" placeholder="size"><br>
        <button type="submit">Send</button>
    </form>
    <ul>
      {% for page in webpage_list %}
        <li>
          {{ page.visited }}, {{ page.tag }}, {{ page.url }}, {{ page.domain }}, {{ page.time_to_load }}, {{ page.load_code }}, {{ page.size }}
        </li>
      {% endfor %}
    </ul>
</body>
</html>